export const FETCH_USER = 'fetch_user'
export const SET_CURRENT_USER = 'set_current_user'
export const AUTH_ERROR = 'auth_error'
export const LOGIN_USER = 'login_user'
export const LOGIN_ERROR = 'login_error'
export const LOGOUT_USER = 'logout_user'
export const LOGOUT_ERROR = 'logout_error'
